# Generated by Django 6.0.7 on 2026-08-03 07:10

import apps.invitations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=255)),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSVP Response',
                'verbose_name_plural': 'RSVP Responses',
                'db_table': 'rsvp_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=apps.invitations.models.generate_slug, max_length=20, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('custom_subdomain', models.SlugField(blank=True, null=True, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='templates_app.template')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
