# Generated by Django 6.0.7 on 2026-08-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSVPResponse',
        ),
    ]
