# Generated by Django 6.0.7 on 2026-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='content',
            field=models.JSONField(default=dict, help_text="User-supplied content keyed by the template's field_schema field keys."),
        ),
    ]
