# Generated by Django 6.0.7 on 2026-08-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_phase15_populate_content_from_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text="User-supplied content keyed by the template's field_schema field keys."),
        ),
    ]
