# Generated by Django 6.0.7 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_alter_invitation_config_alter_invitation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
