# Generated by Django 6.0.7 on 2026-08-03 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('preview_url', models.URLField(blank=True)),
                ('animation_config', models.JSONField(default=dict)),
                ('style_tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
