# Generated by Django 6.0.7 on 2026-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tier',
            field=models.CharField(choices=[('classic', 'Classic'), ('royal', 'Royal')], default='classic', max_length=20),
        ),
    ]
