# Generated by Django 6.0.7 on 2026-08-09 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_alter_template_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'template_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='component_key',
            field=models.CharField(blank=True, default='ivory-bloom', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='demo_content',
            field=models.JSONField(default=dict, help_text='Sample content to display on the public template preview page.'),
        ),
        migrations.AddField(
            model_name='template',
            name='field_schema',
            field=models.JSONField(default=dict, help_text='Defines editable fields for this template. Format: {"fields": [{"key": "groom_name", "type": "text", "label": "Groom\'s Name", "max_length": 40, "required": true}, ...]}'),
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='templates', to='templates_app.category'),
        ),
    ]
