# Generated by Django 6.0.7 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_phase15_schema_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark if this template is newly added.'),
        ),
        migrations.AddField(
            model_name='template',
            name='price_inr',
            field=models.PositiveIntegerField(default=999, help_text='Price in INR. 0 means free.'),
        ),
    ]
