# Generated by Django 6.0.7 on 2026-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_template_is_new_template_price_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tier',
            field=models.CharField(choices=[('new', 'New'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
    ]
