# Generated by Django 6.0.7 on 2026-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0005_alter_template_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tier',
            field=models.CharField(choices=[('new', 'New'), ('elegant', 'Elegant'), ('luxe', 'Luxe')], default='elegant', max_length=20),
        ),
    ]
